Algoritmo "Atividade Antecessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Victor Santos Rohod
// Autor(a)    : Luiz Henrique Maciel de Oliveira
// Data atual  : 23/02/2024

Var

n1 : real

Inicio

escreval("Bom dia, digite um número e lhe diremos qual é o seu antecessor.")

leia(n1)

escreval ("Este é o seu número:" , n1)

escreval("Este é o antecessor do número escolhido:" , n1 - 1)

Fimalgoritmo