Algoritmo "Nota escolar (não é atividade)"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2024
Var

Aprovado, Reprovado, Recuperação: real
notaPrimeiroBimestre , notaSegundoBimestre : real
notaTerceiroBimestre , notaQuartoBimestre : real

Inicio

escreval("Insira as suas notas de cada bimestre e verifique se está aprovado")
escreval("")
leia(notaPrimeiroBimestre)













Fimalgoritmo