Algoritmo "Matriz"
// Disciplina: [Linguagem e Lógica de Programação]
// Professor: Victor Santos Rohod
// Descrição: Explicação do que são matrizes
// Autor(a): Luiz Henrique Maciel de Oliveira
// Data atual: 06/03/2024
Var

m : vetor[1..3, 1..2] de inteiro
l , c : inteiro

//l = linha ; c = coluna

Inicio

para l <- 1 ate 3 faca
  para c <- 1 ate 2 faca
   leia(m[l,c])
  fimpara
fimpara

Fimalgoritmo