Algoritmo "Atividade Antecessor"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Victor Santos Rohod
// Autor(a)    : Luiz Henrique Maciel de Oliveira
// Data atual  : 23/02/2024

Var

numero1 , operacao : real

Inicio

escreval("Bom dia, digite um número e lhe diremos qual é o seu antecessor.")

leia(numero1)

operacao <- (numero1 - 1)

escreval ("Este é o seu número:" , numero1)

escreval("Este é o seu antecessor:" , operacao)

Fimalgoritmo